<?php
/** @var Template $block */
/** @var Escaper $escaper */

/** @var SecureHtmlRenderer $secureRenderer */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use MageOS\ThemeOptimization\ViewModel\SpeculationRules;

/** @var SpeculationRules $viewModel */
$viewModel = $block->getViewModel();
?>
<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'speculationrules'],
    $viewModel->getSpeculationRulesJson(),
    false
) ?>
